// Declare the Setup function

function setup() {
// create a canvas 1280 px wide, by 720 px high

  //establish framerate of 10
    frameRate(5);

    createCanvas( 580, 580);

// using the math random function, in conjunction with the 'floor' addition, create a variable
// between 1 and 30


  }


function draw(){

// store random variable generated by random function.

var var1 = var1;

var1 = floor((random()*30)+1);

  if (var1 >= 15) {

// if

    background('silver');
    fill('maroon');
    ellipse( width /2, height /2, 120, 120);

  }

  else if (var1 < 15) {

    background('maroon');
    rectMode(CENTER);
    fill('silver');
    rect( width /2, height /2, 150, 50);
  }
}
